apiVersion: v1
kind: Service
metadata:
  name: flask-helm-example
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: flask-helm-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-helm-example
  labels:
    app: flask-helm-example
spec:
  selector:
    matchLabels:
      app: flask-helm-example
  template:
    metadata:
      labels:
        app: flask-helm-example
    spec:
      containers:
      - name: flask-helm-example
        image: {{ .Values.registry }}:{{ .Values.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
